npdp_server:
  debug:
    flask_debug: on # on or false

  host:
    ip: ip address
    port: port number

  # a secret key for Flask application.
  secret_key: some secret key

  database:
    type: neo4j
    host:
      ip: ip address
      port: port number
    account:
      user: user
      password: password
